import { FiAward } from 'react-icons/fi';
import { Link } from 'react-router-dom';

const AIMentorCard = () => (
  <div className="md:col-span-2 bg-white rounded-xl border border-gray-200 p-6">
    <div className="flex items-center justify-between mb-4">
      <h2 className="text-lg font-semibold text-black">AI Mock test</h2>
      <div className="bg-black p-2 rounded-lg">
        <FiAward className="text-white" />
      </div>
    </div>
    <div className="space-y-4">
      <p className="text-gray-600">
        Ai generated quiz get different q everytime
      </p>
      <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
        <h3 className="font-medium text-black mb-2">General rules:</h3>
        <ul className="list-disc list-inside text-gray-700 space-y-1">
          <li>Atend 5 questions</li>
          <li>Questions are generated by Ai</li>
          <li>Topic is programming language</li>
          <li>Minium 3 marks to pass</li>
        </ul>
      </div>
      <Link to="/aiquiz"><button className="w-full bg-black hover:bg-gray-800 text-white py-3 px-4 rounded-lg transition-colors flex items-center justify-center">
        <FiAward className="mr-2" />
        Start Ai quiz
      </button></Link>
    </div>
  </div>
);

export default AIMentorCard;